# Generated by Django 3.2.11 on 2022-01-18 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 22, 30, 47, 67935))),
                ('last_order', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 22, 30, 47, 67959))),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('front_img_url', models.CharField(max_length=100)),
                ('back_img_url', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_size', models.CharField(max_length=10)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 22, 30, 47, 68761))),
                ('order_num', models.IntegerField(default=1)),
                ('buyer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shirtapp.buyer')),
                ('shirt_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shirtapp.shirt')),
            ],
        ),
    ]
