# Generated by Django 3.2.11 on 2022-01-18 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 22, 36, 45, 978487)),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_order',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 22, 36, 45, 978532)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 22, 36, 45, 980019)),
        ),
    ]
