# Generated by Django 4.0.3 on 2022-04-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirtapp', '0003_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
    ]
