# Generated by Django 3.2.11 on 2022-01-21 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtapp', '0004_auto_20220121_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='front_img_url',
            new_name='pic1_img_url',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='back_img_url',
            new_name='pic2_img_url',
        ),
        migrations.AddField(
            model_name='shirt',
            name='pic1_title',
            field=models.CharField(default='Front', max_length=100),
        ),
        migrations.AddField(
            model_name='shirt',
            name='pic2_title',
            field=models.CharField(default='Back', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 23, 14, 35, 309315)),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_order',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 23, 14, 35, 309463)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 23, 14, 35, 315862)),
        ),
    ]
