# Generated by Django 3.2.11 on 2022-02-02 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtapp', '0006_auto_20220202_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 5, 6, 51, 299856)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 5, 6, 51, 304412)),
        ),
    ]
