# Generated by Django 3.2.11 on 2022-02-02 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shirtapp', '0008_auto_20220202_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
