# Generated by Django 3.2.11 on 2022-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtapp', '0010_auto_20220215_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
