# Generated by Django 3.2.11 on 2022-02-18 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirtapp', '0011_auto_20220215_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(default='xxx', max_length=15)),
                ('name', models.CharField(default='none', max_length=255)),
                ('created_on', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shirt_id',
            new_name='shirt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_id',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.AddField(
            model_name='order',
            name='advocate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shirtapp.advocate'),
        ),
    ]
